# ======================================================================
# Trailblazer Jekyll Theme — _config.yml
# Owner: Swarnil (ImSwarnil) — Portfolio • Résumé • Blog • Products I Use
# ======================================================================
# TABLE OF CONTENTS (most edited at top)
#  0) 🔑 Site Identity & SEO Essentials
#  1) 🌏 URL, Build, Markdown & Sass
#  2) 👤 Author & Social
#  3) 🧭 Navigation (with dropdowns + Phosphor bold icons)
#  4) 🗂 Collections (posts, docs, projects, resume, courses, videos, uses, products)
#  5) 🧬 Defaults (layouts, social images)
#  6) 🪄 Plugins (gems) & Settings
#  7) 🧱 Assets, Favicons & Web Manifest
#  8) 🔍 Search (optional)
#  9) 📈 Analytics (optional)
# 10) 🤖 Robots & Crawling
# 11) 🅰️ Fonts
# 12) 🧪 Feature Flags / Misc
# ======================================================================


# ----------------------------------------------------------------------
# 0) 🔑 Site Identity & SEO Essentials
# ----------------------------------------------------------------------
title: "Trailblazer — Swarnil"            # Primary site title (SEO <title>)
short_name: "Trailblazer"                  # PWA short name
description: "Filmmaker & Salesforce Engineer. Portfolio, projects, and stories with a Deadpool wink and a Jack Sparrow plan."
lang: en-IN                                # Audience language
timezone: Asia/Kolkata                     # Consistent post dates for India
url: "https://trailblzer.imswarnil.com"    # Canonical site URL (no trailing slash)
baseurl: ""                                # If hosted at a subpath, set like "/blog"
logo: "/assets/logos/logo.svg"             # Used by jekyll-seo-tag
image: "/assets/default-social-image.png"  # Social share default
permalink: pretty                          # /yyyy/mm/dd/title/ → /title/
excerpt_separator: "<!-- more -->"

# SEO Structured Data (kept simple; expand if needed)
seo:
  type: "Person"                           # Person or Organization
  name: "Raja Swarnil Singhai"
  job_title: "Salesforce Application Developer & Filmmaker"
  same_as:
    - "https://www.youtube.com/@ImSwarnil"
    - "https://twitter.com/ImSwarnil"
    - "https://github.com/ImSwarnil"
    - "https://www.linkedin.com/in/imswarnil"

# ----------------------------------------------------------------------
# 1) 🌏 URL, Build, Markdown & Sass
# ----------------------------------------------------------------------
sass:
  quiet_deps: true
  style: compressed

markdown: CommonMark
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]
css_inline: true                           # Inlines compiled CSS into <head> for speed


# ----------------------------------------------------------------------
# 2) 👤 Author & Social
# ----------------------------------------------------------------------
author: "Swarnil"
email: "hello@imswarnil.com"               # TODO: update
twitter:
  username: ImSwarnil
social:
  name: "Raja Swarnil Singhai"
  links:
    - "https://twitter.com/ImSwarnil"
    - "https://github.com/ImSwarnil"
    - "https://www.linkedin.com/in/imswarnil"
    - "https://www.instagram.com/imswarnil"

# Sidebar / Footer quick links
social_links:
  Twitter:  "https://twitter.com/ImSwarnil"
  LinkedIn: "https://www.linkedin.com/in/imswarnil"
  GitHub:   "https://github.com/ImSwarnil"
  YouTube:  "https://www.youtube.com/@ImSwarnil"
  link:     "https://imswarnil.com"
  RSS:      "/feed.xml"


# ----------------------------------------------------------------------
# 3) 🧭 Navigation (with dropdowns + Phosphor bold icons)
# Tip: icon classes use Phosphor "bold" set (e.g., ph-bold ph-user, ph-film-reel)
# Your templates should render icon classes from these entries.
# ----------------------------------------------------------------------
navigation_header:
  - title: "Home"
    url: "/"
    icon: "ph-bold ph-house"
  - title: "About"
    url: "/about/"
    icon: "ph-bold ph-user"
  - title: "Portfolio"
    icon: "ph-bold ph-briefcase"
    children:
      - title: "Projects"
        url: "/projects/"
        icon: "ph-bold ph-circles-three-plus"
      - title: "Videos"
        url: "/videos/"
        icon: "ph-bold ph-film-reel"
      - title: "Web Series"
        url: "/webseries/"
        icon: "ph-bold ph-play-circle"
      - title: "Résumé"
        url: "/resume/"
        icon: "ph-bold ph-file-text"
  - title: "Blog"
    url: "/blog/"
    icon: "ph-bold ph-notebook"
  - title: "Courses"
    url: "/courses/"
    icon: "ph-bold ph-graduation-cap"
  - title: "Uses"
    url: "/uses/"
    icon: "ph-bold ph-wrench"
  - title: "Products"
    url: "/products/"
    icon: "ph-bold ph-bag"
  - title: "Docs"
    url: "/docs/"
    icon: "ph-bold ph-book"
  - title: "Search"
    url: "/search/"
    icon: "ph-bold ph-magnifying-glass"

navigation_footer:
  - title: "Built by ImSwarnil"
    url: "https://imswarnil.com"
  - title: "Theme Repo"
    url: "https://github.com/ImSwarnil/trailblazer-jekyll"  # TODO: update


# ----------------------------------------------------------------------
# 4) 🗂 Collections
# Add what you actually use; others can be removed.
# ----------------------------------------------------------------------
collections:
  posts:
    title: "Blog"
    output: true
    description: "Stories, breakdowns, and dev notes"
  docs:
    output: true
    permalink: "/docs/:path/"
  projects:
    output: true
    permalink: "/projects/:path/"
  resume:
    output: true
    permalink: "/resume/:path/"
  courses:
    output: true
    permalink: "/courses/:path/"
  videos:
    output: true
    permalink: "/videos/:path/"
  webseries:
    output: true
    permalink: "/webseries/:path/"
  uses:             # “Products I use” / gear / apps
    output: true
    permalink: "/uses/:path/"
  products:         # Your own products or affiliate kits
    output: true
    permalink: "/products/:path/"

# Optional collection feature content for blog index
posts_feature:
  feature_text: "Welcome to the blog"
  feature_image: "https://picsum.photos/2560/600?image=866"


# ----------------------------------------------------------------------
# 5) 🧬 Defaults (layouts, social images)
# Applies to groups of pages by path/type to avoid repeating front matter.
# ----------------------------------------------------------------------
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/default-social-image.png"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "docs"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "resume"
    values:
      layout: "resume"
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "course"
  - scope:
      path: ""
      type: "videos"
    values:
      layout: "video"
  - scope:
      path: ""
      type: "uses"
    values:
      layout: "uses"
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"


# ----------------------------------------------------------------------
# 6) 🪄 Plugins (gems) & Settings
# Keep essentials; comment optionals you don't need.
# ----------------------------------------------------------------------
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-include-cache
  - jemoji
  - jekyll-commonmark
  # - jekyll-algolia            # Optional search (see Section 8)

paginate: 10
paginate_path: "/blog/page:num"
jekyll-mentions: https://twitter.com

# Repo metadata (used by some templates)
repo: "https://github.com/ImSwarnil/trailblazer-jekyll"       # TODO
github_repo_url: "https://github.com/ImSwarnil/trailblazer-jekyll"
sponsor_url: "https://github.com/sponsors/ImSwarnil"

# Excludes from build
exclude:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - screenshot.png
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache


# ----------------------------------------------------------------------
# 7) 🧱 Assets, Favicons & Web Manifest
# ----------------------------------------------------------------------
favicons:
  16:   "/assets/logos/logo@16px.png"
  32:   "/assets/logos/logo@32px.png"
  96:   "/assets/logos/logo@96px.png"
  120:  "/assets/logos/logo@120px.png"
  144:  "/assets/logos/logo@144px.png"
  180:  "/assets/logos/logo@180px.png"
  512:  "/assets/logos/logo@512px.png"
  1024: "/assets/logos/logo@1024px.png"


# ----------------------------------------------------------------------
# 9) 📈 Analytics (optional)
# Use ONE provider at a time to avoid dueling scripts.
# ----------------------------------------------------------------------
analytics:
  provider: "ga4"            # "ga4" | "gtag" | "plausible" | "umami" | false
  ga4_measurement_id: ""     # TODO
  anonymize_ip: true

# Legacy keys (leave empty if using Section 9):
google_analytics: ""
google_analytics_anonymize_ip: ""


# ----------------------------------------------------------------------
# 10) 🤖 Robots & Crawling
# ----------------------------------------------------------------------
robots:
  allow: ["/"]
  disallow: []
  sitemap: "/sitemap.xml"
  crawl_delay: 10

# Canonical defaults for templates that generate them
canonical:
  enabled: true


# ----------------------------------------------------------------------
# 11) 🅰️ Fonts
# Keep URLs minimal; combine when possible.
# ----------------------------------------------------------------------
fonts:
  preconnect_urls:
    - "https://fonts.gstatic.com"
  font_urls:
    - "https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap"


# ----------------------------------------------------------------------
# 12) 🧪 Feature Flags / Misc Site Vars (used in layouts/partials)
# These are handy knobs you’ll read from Liquid.
# ----------------------------------------------------------------------
feature_flags:
  show_hero_badge: true
  show_subscribe_cta: true
  lazyload_images: true
  dark_mode: true

hero:
  title: "Life. Code. Camera. Repeat."
  subtitle: "Salesforce CRM Analytics & cinematic storytelling—because dashboards deserve drama."
  company: "Your Company"                  # or pull from data file
  location: "Bengaluru, India"

sharing_links:
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
