# ======================================================================
# Trailblazer Jekyll Theme — _config.yml (Portfolio • Resume • Blog)
# Owner: Swarnil / Imswarnil
# ======================================================================
# TABLE OF CONTENTS (edit-heavy at top)
#  0) 🔑 Identity & SEO
#  1) 🧭 Navigation (dropdowns + Phosphor bold icons)
#  2) 🧾 Résumé Data (skills • work timeline • achievements • awards • certs)
#  3) 🖼 Media & Images (hero, gallery, social defaults)
#  4) 🗂 Collections (posts, docs, projects, resume, courses, videos, uses, products)
#  5) 🧬 Defaults (layouts)
#  6) 🧪 Integrations (AdSense, Formspree, GA4, Microsoft Clarity)
#  7) 🔌 Plugins (gems) & Build Settings
#  8) 🧱 Favicons (Manifest is in a separate file)
#  9) 🅰️ Fonts
# 10) 🤖 Robots
# 11) 🧯 Misc / Feature Flags
# 12) 🚫 Excludes
# ======================================================================

# ----------------------------------------------------------------------
# 0) 🔑 Identity & SEO
# ----------------------------------------------------------------------
title: "Trailblazer — Swarnil"
short_name: "Trailblazer"
description: "Filmmaker & Salesforce Engineer. Portfolio, projects, and stories with a Deadpool wink and a Jack Sparrow plan."
lang: en-IN
timezone: Asia/Kolkata
url: "https://trailblzer.imswarnil.com"
baseurl: ""
logo: "/assets/logos/logo.svg"
image: "/assets/default-social-image.png"   # default social share image
permalink: pretty
excerpt_separator: "<!-- more -->"

seo:
  type: "Person"
  name: "Raja Swarnil Singhai"
  job_title: "Salesforce Application Developer & Filmmaker"
  same_as:
    - "https://www.youtube.com/@ImSwarnil"
    - "https://twitter.com/ImSwarnil"
    - "https://github.com/ImSwarnil"
    - "https://www.linkedin.com/in/imswarnil"

author: "Swarnil"
email: "hello@imswarnil.com"

# ----------------------------------------------------------------------
# 1) 🧭 Navigation (dropdowns + Phosphor bold icons)
#    Your nav include should render icon classes: <i class="{{ item.icon }}"></i>
# ----------------------------------------------------------------------
navigation_header:
  - title: "Home"
    url: "/"
    icon: "ph-bold ph-house"
  - title: "About"
    url: "/about/"
    icon: "ph-bold ph-user"
  - title: "Portfolio"
    icon: "ph-bold ph-briefcase"
    children:
      - title: "Projects"
        url: "/projects/"
        icon: "ph-bold ph-circles-three-plus"
      - title: "Videos"
        url: "/videos/"
        icon: "ph-bold ph-film-reel"
      - title: "Web Series"
        url: "/webseries/"
        icon: "ph-bold ph-play-circle"
      - title: "Gallery"
        url: "/gallery/"
        icon: "ph-bold ph-images"
      - title: "Résumé"
        url: "/resume/"
        icon: "ph-bold ph-file-text"
  - title: "Blog"
    url: "/blog/"
    icon: "ph-bold ph-notebook"
  - title: "Courses"
    url: "/courses/"
    icon: "ph-bold ph-graduation-cap"
  - title: "Uses"
    url: "/uses/"
    icon: "ph-bold ph-wrench"
  - title: "Products"
    url: "/products/"
    icon: "ph-bold ph-bag"
  - title: "Docs"
    url: "/docs/"
    icon: "ph-bold ph-book"
  - title: "Search"
    url: "/search/"
    icon: "ph-bold ph-magnifying-glass"

navigation_footer:
  - title: "Built by ImSwarnil"
    url: "https://imswarnil.com"
  - title: "Theme Repo"
    url: "https://github.com/ImSwarnil/trailblazer-jekyll"  # TODO

social_links:
  Twitter:  "https://twitter.com/ImSwarnil"
  LinkedIn: "https://www.linkedin.com/in/imswarnil"
  GitHub:   "https://github.com/ImSwarnil"
  YouTube:  "https://www.youtube.com/@ImSwarnil"
  link:     "https://imswarnil.com"
  RSS:      "/feed.xml"

# ----------------------------------------------------------------------
# 2) 🧾 Résumé Data (edit here; render in /resume/ layout)
# ----------------------------------------------------------------------
resume:
  headline: "Salesforce CRM Analytics • Filmmaker • Story-led Engineer"
  summary: >
    Salesforce CRM Analytics from SAQL to embedded dashboards. I craft products,
    stories, and dashboards with cinematic pacing and measurable outcomes.
  location: "Bengaluru, India"
  availability: "Open to selective collaborations & speaking."

  # Top skills grouped (you can show meters/stars via 'level')
  skills:
    - group: "Salesforce & Analytics"
      items:
        - { name: "CRM Analytics (TCRM/EA)", level: 5 }
        - { name: "SAQL & Bindings", level: 5 }
        - { name: "Dashboard JSON", level: 5 }
        - { name: "Lightning Embedding", level: 4 }
        - { name: "Apex, LWC", level: 4 }
    - group: "Data & Viz"
      items:
        - { name: "Recipes/Dataflows", level: 5 }
        - { name: "Modeling & KPIs", level: 4 }
        - { name: "Storyboarding Dashboards", level: 5 }
    - group: "Film & Creative"
      items:
        - { name: "Direction & Editing", level: 5 }
        - { name: "Scriptwriting", level: 4 }
        - { name: "Cinematography", level: 4 }
    - group: "Web & Theming"
      items:
        - { name: "Jekyll & SCSS", level: 5 }
        - { name: "Bulma/SLDS/Tailwind", level: 4 }
        - { name: "SEO & Performance", level: 4 }

  # Work timeline: newest first
  work:
    - company: "Twilio / (Salesforce CRM-Analytics focus)"
      logo: "/assets/logos/twilio.svg"
      role: "Software Engineer"
      period: "2024 — Present"
      location: "Bengaluru"
      summary: "Built creator-grade analytics experiences inside Salesforce; Tweek-Week prototypes that stuck."
      highlights:
        - "AE Quote Dashboard with Bento UI; CPQ Embedded AI assistant."
        - "Credit-memo analytics and Quote Insights experiments."
        - "Improved dashboard performance & adoption with story-first UX."
      tech: ["CRM Analytics", "SAQL", "Apex", "LWC", "CPQ", "Jekyll"]
      links:
        - { label: "Demo write-up", url: "/projects/ae-quote-dashboard/" }
    - company: "Accenture"
      logo: "/assets/logos/accenture.svg"
      role: "Application Development Analyst"
      period: "2022 — 2024"
      location: "Bengaluru"
      summary: "Delivered Salesforce features at scale; mentored analysts; built reusable UI kits."
      highlights:
        - "CPQ dashboards; embedded CRM Analytics with guardrails."
        - "Internal Jekyll theme & docs for faster delivery."
      tech: ["Salesforce", "CPQ", "CRM Analytics", "Jekyll"]
    - company: "Cognizant"
      logo: "/assets/logos/cognizant.svg"
      role: "Programmer Analyst"
      period: "2020 — 2022"
      location: "Bengaluru"
      summary: "First enterprise rodeo—automation, data pipelines, and client storytelling."
      highlights:
        - "Stabilized dataflows and SAQL queries for exec views."
      tech: ["Salesforce", "Dataflows", "APIs"]

  # Education (optional)
  education:
    - school: "LNCT"
      logo: "/assets/logos/lnct.svg"
      degree: "B.E., Computer Science"
      period: "2016 — 2020"
      location: "Bhopal, India"

  # Certifications
  certifications:
    - name: "Salesforce Certified Administrator"
      org: "Salesforce"
      date: "2023-08-01"
      id: "XXXX-ADMIN"
      url: "https://trailhead.salesforce.com/credentials"
      badge: "/assets/badges/sf-admin.png"
    - name: "Tableau CRM & Einstein Discovery Consultant"
      org: "Salesforce"
      date: "2024-03-10"
      id: "XXXX-TCRM"
      url: "https://trailhead.salesforce.com/credentials"
      badge: "/assets/badges/tcrm.png"

  # Awards / Achievements
  awards:
    - title: "Tweek Week Winner — Analytics Experience"
      by: "Twilio"
      year: "2025"
      note: "Prototype to production path for CPQ analytics."
    - title: "YouTube Silver-ish Soul"
      by: "ImSwarnil Fam"
      year: "Evergreen"
      note: "17k subs pre-hiatus; comeback arc initiated."

  # Quick facts for a sidebar card
  quickfacts:
    - { label: "Experience", value: "5+ years" }
    - { label: "Specialty", value: "CRM Analytics & Film" }
    - { label: "Location", value: "Bengaluru" }

# ----------------------------------------------------------------------
# 3) 🖼 Media & Images (hero + gallery; manifest handled separately)
# ----------------------------------------------------------------------
media:
  hero:
    title: "Life. Code. Camera. Repeat."
    subtitle: "Dashboards with drama. Stories with data."
    company: "Your Company"
    location: "Bengaluru, India"
    image: "/assets/hero/hero-portrait.png"     # right-side hero image
    pattern: "/assets/hero/pattern.svg"         # subtle background pattern
  gallery:
    enabled: true
    items:
      - { src: "/assets/gallery/frame-01.jpg", alt: "Cinematic still 1" }
      - { src: "/assets/gallery/frame-02.jpg", alt: "Cinematic still 2" }
      - { src: "/assets/gallery/frame-03.jpg", alt: "Cinematic still 3" }

# ----------------------------------------------------------------------
# 4) 🗂 Collections
# ----------------------------------------------------------------------
collections:
  posts:     { title: "Blog", output: true, description: "Stories, breakdowns, and dev notes" }
  docs:      { output: true, permalink: "/docs/:path/" }
  projects:  { output: true, permalink: "/projects/:path/" }
  resume:    { output: true, permalink: "/resume/:path/" }
  courses:   { output: true, permalink: "/courses/:path/" }
  videos:    { output: true, permalink: "/videos/:path/" }
  webseries: { output: true, permalink: "/webseries/:path/" }
  uses:      { output: true, permalink: "/uses/:path/" }
  products:  { output: true, permalink: "/products/:path/" }

posts_feature:
  feature_text: "Welcome to the blog"
  feature_image: "https://picsum.photos/2560/600?image=866"

# ----------------------------------------------------------------------
# 5) 🧬 Defaults (layouts)
# ----------------------------------------------------------------------
defaults:
  - scope: { path: "" }
    values: { image: "/assets/default-social-image.png" }
  - scope: { path: "", type: "posts" }     ; values: { layout: "post" }
  - scope: { path: "", type: "pages" }     ; values: { layout: "page" }
  - scope: { path: "", type: "docs" }      ; values: { layout: "docs" }
  - scope: { path: "", type: "projects" }  ; values: { layout: "project" }
  - scope: { path: "", type: "resume" }    ; values: { layout: "resume" }
  - scope: { path: "", type: "courses" }   ; values: { layout: "course" }
  - scope: { path: "", type: "videos" }    ; values: { layout: "video" }
  - scope: { path: "", type: "uses" }      ; values: { layout: "uses" }
  - scope: { path: "", type: "products" }  ; values: { layout: "product" }

# ----------------------------------------------------------------------
# 6) 🧪 Integrations (turn keys on, templates include scripts via these)
# ----------------------------------------------------------------------
integrations:
  adsense:
    enabled: false
    publisher_id: "ca-pub-XXXXXXXXXXXXXXXX"    # TODO
    enable_auto_ads: true
  formspree:
    enabled: false
    endpoint: "https://formspree.io/f/XXXXXXXX" # TODO
  analytics:
    provider: "ga4"                             # ga4|plausible|umami|false
    ga4_measurement_id: ""                      # TODO if provider=ga4
    anonymize_ip: true
  clarity:
    enabled: false
    project_id: ""                               # Microsoft Clarity Project ID
  # optional: verify site ownership
  webmaster_verifications:
    google: ""                                   # e.g., google-site-verification meta
    bing: ""
    yandex: ""
    pinterest: ""

# ----------------------------------------------------------------------
# 7) 🔌 Plugins (gems) & Build Settings
# ----------------------------------------------------------------------
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-include-cache
  - jemoji
  - jekyll-commonmark
  # - jekyll-algolia  # enable if you wire Algolia

paginate: 10
paginate_path: "/blog/page:num"

markdown: CommonMark
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

sass:
  quiet_deps: true
  style: compressed
css_inline: true

jekyll-mentions: https://twitter.com

repo: "https://github.com/ImSwarnil/trailblazer-jekyll"       # TODO
github_repo_url: "https://github.com/ImSwarnil/trailblazer-jekyll"
sponsor_url: "https://github.com/sponsors/ImSwarnil"

# ----------------------------------------------------------------------
# 8) 🧱 Favicons (Manifest is managed in a separate file 👍)
# ----------------------------------------------------------------------
favicons:
  16:   "/assets/logos/logo@16px.png"
  32:   "/assets/logos/logo@32px.png"
  96:   "/assets/logos/logo@96px.png"
  120:  "/assets/logos/logo@120px.png"
  144:  "/assets/logos/logo@144px.png"
  180:  "/assets/logos/logo@180px.png"
  512:  "/assets/logos/logo@512px.png"
  1024: "/assets/logos/logo@1024px.png"

# ----------------------------------------------------------------------
# 9) 🅰️ Fonts
# ----------------------------------------------------------------------
fonts:
  preconnect_urls:
    - "https://fonts.gstatic.com"
  font_urls:
    - "https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap"

# ----------------------------------------------------------------------
# 10) 🤖 Robots
# ----------------------------------------------------------------------
robots:
  allow: ["/"]
  disallow: []
  sitemap: "/sitemap.xml"
  crawl_delay: 10

# ----------------------------------------------------------------------
# 11) 🧯 Misc / Feature Flags
# ----------------------------------------------------------------------
feature_flags:
  show_hero_badge: true
  show_subscribe_cta: true
  lazyload_images: true
  dark_mode: true

sharing_links:
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

# ----------------------------------------------------------------------
# 12) 🚫 Excludes
# ----------------------------------------------------------------------
exclude:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - screenshot.png
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache
